### PR TITLE
Move close contact and noncovalent i18n to cpp files

### LINKED ISSUE #2556: translation failure
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 4f543410b298ed8794fb9d873d771548100d198b
 - avogadro-i18n: OpenChemistry/avogadro-i18n@a559f48ab608f27f2c936a53aac8b59f7c47bffb
 - Qt: 6.10.1

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Compiler GCC 15.2.1

**Describe the bug**

Some texts are not localized even though they are translated.

**To Reproduce**

- Display Types →
  - Close Contacts, View Configuration
  - Non-Covalent, View Configuration

**Expected behavior**

“Contact,” “Salt Bridge,” and so forth are localized if translated.

https://github.com/OpenChemistry/avogadrolibs/blob/4f543410b298ed8794fb9d873d771548100d198b/avogadro/qtplugins/closecontacts/closecontacts.h#L54-L56

https://github.com/OpenChemistry/avogadrolibs/blob/4f543410b298ed8794fb9d873d771548100d198b/avogadro/qtplugins/noncovalent/noncovalent.h#L53-L55

**Screenshots**

de_DE
de_DE

https://github.com/OpenChemistry/avogadrolibs/blob/4f543410b298ed8794fb9d873d771548100d198b/i18n/de.po#L2380-L2390

fr_FR
fr_FR  

https://github.com/OpenChemistry/avogadrolibs/blob/4f543410b298ed8794fb9d873d771548100d198b/i18n/fr.po#L4164-L4170

**Additional context**

Possibly related:

```
/home/runner/work/avogadro-i18n/avogadro-i18n/openchemistry/avogadrolibs/avogadro/qtplugins/closecontacts/closecontacts.h:54: Qualifying with unknown namespace/class ::std
Scanning directory '..'...
/home/runner/work/avogadro-i18n/avogadro-i18n/openchemistry/avogadrolibs/avogadro/qtplugins/noncovalent/noncovalent.h:53: Qualifying with unknown namespace/class ::std
```

https://github.com/OpenChemistry/avogadro-i18n/actions/runs/21325890851/job/61382887904#step:7:44

### PR DESCRIPTION
**Pull request by ghutchis**
Should fix #2556

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

File: avogadro/qtplugins/closecontacts/closecontacts.cpp [hunk 1]
```diff
@@ -252,7 +252,19 @@ QWidget* CloseContacts::setupWidget()
...
+      case 0:
+        tabs->addTab(page, tr("Contact"));
+        break;
+      case 1:
+        tabs->addTab(page, tr("Salt Bridge"));
+        break;
+      case 2:
+        tabs->addTab(page, tr("Repulsive"));
+        break;
+      default:
```
Comment (e-kwsm) [inline avogadro/qtplugins/closecontacts/closecontacts.cpp]: Unrelated to i18n, but compilation fails at this line.
```suggestion
      default:;
```

**Comment by ghutchis** [comment]
Thanks for the bug reports - fortunately this one was easy to fix!
