### PR TITLE
fix #2176 (¹¹⁸Og and ¹¹⁹Uue)

### LINKED ISSUE #2176: CJSON: ¹¹⁸Og and ¹¹⁹Uue problem
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 66d4e054de2d6bbefa3cbb09f7e7e355e8e8145e
 - Qt: 6.9.2

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Compiler: GCC 15.2.1

**Describe the bug**

- ¹¹⁷Ts is rendered as a red sphere
- ¹¹⁸Og is *not* shown
- ¹¹⁹Uue causes *crash*
- ¹²⁰Ubn and ¹²¹Ubu are rejected: &ldquo;Error: atomic number is invalid&rdquo; (*no* crash)

**To Reproduce**

```json
{"chemicalJson": 1,
 "atoms": {"coords": {"3d": [0.0, 0.0, 0.0]}, "elements": {"number": [118]}}}
```

Open the above CJSON → 1 atom is loaded but nothing is displayed.

Change the atomic number to 119 → crash:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  bitset::set: __position (which is 119) >= _Nb (which is 119)
zsh: IOT instruction  ./avogadro2
```

**Expected behavior**

Og is rendered correctly.

### PR DESCRIPTION
**Pull request by e-kwsm**
fix #2176

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by e-kwsm** [comment]
https://github.com/OpenChemistry/avogadrolibs/blob/66d4e054de2d6bbefa3cbb09f7e7e355e8e8145e/avogadro/core/molecule.cpp#L563-L567

I am not confident, but

```diff
--- a/avogadro/core/molecule.cpp
+++ b/avogadro/core/molecule.cpp
@@ -563,3 +563,3 @@ Molecule::AtomType Molecule::addAtom(unsigned char number)
   // we're not going to easily handle custom elements
-  if (number <= element_count)
+  if (number < element_count)
     m_elements.set(number);
```

File: avogadro/core/elementdata.h [hunk 1]
```diff
@@ -1,9 +1,11 @@
 #ifndef AVOGADRO_CORE_ELEMENTS_DATA
 #define AVOGADRO_CORE_ELEMENTS_DATA
 
+#include "elements.h"
+
 namespace Avogadro::Core {
 
-const char* element_symbols[] = {
+const char* const element_symbols[element_count] = {
```
Comment (e-kwsm) [inline avogadro/core/elementdata.h:8]: If a C array is replaced with `std::array` and `_GLIBCXX_CONCEPT_CHECKS` is defined (implied by `-O0`), boundaries are checked at runtime.

&mdash;or ASan.

Comment (ghutchis) [reply avogadro/core/elementdata.h:8]: I'm not sure why ASan didn't catch this. Clearly we need more unit tests.

**Review by ghutchis — APPROVED** [review]

**Comment by ghutchis** [comment]
The failing builds are unrelated - I'm trying to get the Windows builds fixed soon (VTK issues)
