### PR TITLE
Fix CML support with HDF5 data files

### LINKED ISSUE #2170: test: HDF5 error is detected from an unrelated test case if readFile failed
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: f4f7691ad3bf84f4e9d9a81f30a66e0534232f34
 - Qt: 6.9.2

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Compiler: GCC 15.2.1
 - HDF5: 1.14.6

**Describe the bug**

**To Reproduce**

Apply the following patch:

```diff
--- a/tests/io/cmltest.cpp
+++ b/tests/io/cmltest.cpp
@@ -23,6 +23,14 @@ using Avogadro::Core::Variant;
 using Avogadro::Io::CmlFormat;
 using namespace std::string_literals;

+TEST(CmlTest, readNonExistingFile)
+{
+  CmlFormat cml;
+  Molecule molecule;
+  auto x = cml.readFile("/non-existing.cml", molecule);
+  EXPECT_TRUE(x) << "this must fail";
+}
+
 TEST(CmlTest, readFile)
 {
   CmlFormat cml;
```

```sh
cmake -S . -B build -DENABLE_TESTING=ON -DUSE_HDF5=ON
cmake --build build
ctest --test-dir build -V -R Io-Cml
```

```
Test project /var/tmp/avogadrolibs/build
    Start 23: Io-Cml
1/1 Test #23: Io-Cml ...........................***Failed    0.01 sec
Running main() from /usr/src/debug/gtest/googletest-1.17.0/googletest/src/gtest_main.cc
Note: Google Test filter = CmlTest.*
[==========] Running 9 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 9 tests from CmlTest
[ RUN      ] CmlTest.readNonExistingFile
/var/tmp/avogadrolibs/tests/io/cmltest.cpp:31: Failure
Value of: x
  Actual: false
Expected: true
this must fail

[  FAILED  ] CmlTest.readNonExistingFile (0 ms)
[ RUN      ] CmlTest.readFile
[       OK ] CmlTest.readFile (0 ms)
[ RUN      ] CmlTest.atoms
[       OK ] CmlTest.atoms (0 ms)
[ RUN      ] CmlTest.bonds
[       OK ] CmlTest.bonds (0 ms)
[ RUN      ] CmlTest.fractionalCoords
<?xml version="1.0" encoding="UTF-8"?>
<molecule xmlns="http://www.xml-cml.org/schema" xmlns:cml="http://www.xml-cml.org/dictionary/cml" xmlns:units="http://www.xml-cml.org/unit/nonSi" xmlns:xsd="http://www.w3c.org/2001/XMLSchema" xmlns:iupac="http://www.iupac.org">
  <crystal>
    <scalar title="a" units="units:angstrom">5.3</scalar>
    <scalar title="b" units="units:angstrom">2.4</scalar>
    <scalar title="c" units="units:angstrom">1.8</scalar>
    <scalar title="alpha" units="units:degree">85</scalar>
    <scalar title="beta" units="units:degree">90</scalar>
    <scalar title="gamma" units="units:degree">105</scalar>
  </crystal>
  <atomArray>
    <atom id="a1" elementType="H" xFract="0.5" yFract="0.5" zFract="0.5" />
  </atomArray>
  <bondArray />
  <dataMap />
</molecule>

[       OK ] CmlTest.fractionalCoords (0 ms)
[ RUN      ] CmlTest.saveFile
HDF5-DIAG: Error detected in HDF5 (1.14.6):
  #000: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5F.c line 827 in H5Fopen(): unable to synchronously open file
    major: File accessibility
    minor: Unable to open file
  #001: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5F.c line 788 in H5F__open_api_common(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #002: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5VLcallback.c line 3680 in H5VL_file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5VLcallback.c line 3514 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #004: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5VLnative_file.c line 128 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #005: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5Fint.c line 1897 in H5F_open(): can't try opening file
    major: File accessibility
    minor: Unable to open file
  #006: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5FD.c line 787 in H5FD_open(): can't open file
    major: Virtual File Layer
    minor: Unable to open file
  #007: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5FDsec2.c line 323 in H5FD__sec2_open(): unable to open file: name = 'ethanetmp.cml.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibility
    minor: Unable to open file
[       OK ] CmlTest.saveFile (0 ms)
[ RUN      ] CmlTest.hdf5Matrix
[       OK ] CmlTest.hdf5Matrix (1 ms)
[ RUN      ] CmlTest.writeString
[       OK ] CmlTest.writeString (0 ms)
[ RUN      ] CmlTest.readString
HDF5-DIAG: Error detected in HDF5 (1.14.6):
  #000: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5F.c line 827 in H5Fopen(): unable to synchronously open file
    major: File accessibility
    minor: Unable to open file
  #001: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5F.c line 788 in H5F__open_api_common(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #002: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5VLcallback.c line 3680 in H5VL_file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5VLcallback.c line 3514 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #004: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5VLnative_file.c line 128 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #005: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5Fint.c line 1897 in H5F_open(): can't try opening file
    major: File accessibility
    minor: Unable to open file
  #006: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5FD.c line 787 in H5FD_open(): can't open file
    major: Virtual File Layer
    minor: Unable to open file
  #007: /usr/src/debug/hdf5/hdf5-hdf5_1.14.6/src/H5FDsec2.c line 323 in H5FD__sec2_open(): unable to open file: name = '/var/tmp/avogadrodata/data/cml/ethane.cml.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibility
    minor: Unable to open file
[       OK ] CmlTest.readString (0 ms)
[----------] 9 tests from CmlTest (2 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CmlTest.readNonExistingFile

 1 FAILED TEST


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
	 23 - Io-Cml (Failed)
Errors while running CTest
```

**Expected behavior**

A test case does not affect others, and no HDF5 errors are detected.

### PR DESCRIPTION
**Pull request by ghutchis**
Fixes #2170 - checks if the .hdf5 exists before opening or reading

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved HDF5 file access robustness by adding file existence checks before attempting to open files, preventing errors when files are unavailable.
  * Enhanced error handling to provide more graceful behavior when HDF5 data cannot be accessed.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by ghutchis** [comment]
@coderabbitai review

File: avogadro/io/cmlformat.cpp [hunk 1]
```diff
@@ -368,9 +368,14 @@ class CmlFormatPrivate
     if (!dataNode)
       return true;
 
+    // Check if HDF5 file exists before attempting to open it
+    bool hdf5Available = false;
     Hdf5DataFormat hdf5;
-    hdf5.openFile(filename + ".h5", Hdf5DataFormat::ReadOnly);
-
+    if (std::ifstream(filename + ".h5").good()) {
```
Comment (e-kwsm) [inline avogadro/io/cmlformat.cpp:374]: Thanks, but this requires `<fstream>` (#2447).
