### PR TITLE
fix(templatetool): do not localize functional groups

### LINKED ISSUE #2092: Pathnames to SVG icons are wrongly localized
**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: b3207934648e90391f1530104abbe53990b40f73 or later
 - Qt: 6.9.1

**Desktop version: (please complete the following information):**
 - OS: EndeavourOS
 - Compiler: GCC 15.1.1

**Describe the bug**

Pathnames to template icons are localized, resulting in display error.

**To Reproduce**

1. Launch avogadro under es_ES, hu_HU, ja_JP, ko_KR etc: error message under es_ES is as follows

```
qt.svg: Cannot open file ':/icons/ligands/amida.svg', because: No hay ningún fichero o directorio con ese nombre
qt.svg: Cannot open file ':/icons/ligands/amida.svg', because: No hay ningún fichero o directorio con ese nombre
qt.svg: Cannot open file ':/icons/ligands/amida.svg', because: No hay ningún fichero o directorio con ese nombre
qt.svg: Cannot open file ':/icons/ligands/amida.svg', because: No hay ningún fichero o directorio con ese nombre
```

saying no such file or directory.

**Expected behavior**

Pathnames are not localized and icons are shown.

**Screenshots**

Image

Left: en_US, right: es_ES

### PR DESCRIPTION
**Pull request by e-kwsm**
fix #2092

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

File: avogadro/qtplugins/templatetool/templatetoolwidget.cpp [hunk 1]
```diff
@@ -73,6 +73,16 @@ TemplateToolWidget::TemplateToolWidget(QWidget* parent_)
...
 
+  m_groups << "amide"
+           << "carboxylate"
+           << "ester"
+           << "ethylene"
+           << "ethyne"
+           << "nitro"
+           << "phenyl"
+           << "phosphate"
+           << "sulfonate" << tr("Other…");
```
Comment (e-kwsm) [inline avogadro/qtplugins/templatetool/templatetoolwidget.cpp:84]: I&rsquo;m not confident about the ordering.

https://github.com/OpenChemistry/avogadrolibs/blob/c8c64082ed031e82fb5306306a5b47ed65964ca5/avogadro/qtplugins/templatetool/template.qrc#L34-L42

https://github.com/OpenChemistry/avogadrolibs/blob/c8c64082ed031e82fb5306306a5b47ed65964ca5/avogadro/qtplugins/templatetool/template.qrc#L81-L89

The former is not in dictionary order.

Comment (ghutchis) [reply avogadro/qtplugins/templatetool/templatetoolwidget.cpp:84]: The order doesn't matter in the `.qrc` file, so please feel free to re-arrange.

**Review by ghutchis — APPROVED** [review]
Looks good, thanks!

File: avogadro/qtplugins/templatetool/templatetoolwidget.cpp (hunk 1 above)
Comment (e-kwsm) [reply avogadro/qtplugins/templatetool/templatetoolwidget.cpp:84]: Thanks, .qrc is sorted.

**Comment by ghutchis** [comment]
The Mac / Qt6 build error is unrelated - VTK is having some issues at the moment, so I'm going to merge this.
